// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCoffee.BackendServer.Data;

#nullable disable

namespace WebCoffee.BackendServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.Ban", b =>
                {
                    b.Property<string>("SoBan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChuBAN")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoKV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenBan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiBan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SoBan");

                    b.HasIndex("SoKV");

                    b.ToTable("BAN");

                    b.HasData(
                        new
                        {
                            SoBan = "B01",
                            SoKV = "KV01",
                            TenBan = "Bàn 1 Trệt",
                            TrangThaiBan = "Trống"
                        },
                        new
                        {
                            SoBan = "B02",
                            SoKV = "KV01",
                            TenBan = "Bàn 2 Trệt",
                            TrangThaiBan = "Trống"
                        },
                        new
                        {
                            SoBan = "B03",
                            SoKV = "KV02",
                            TenBan = "Bàn 1 Sân Thượng",
                            TrangThaiBan = "Trống"
                        });
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.CTHD", b =>
                {
                    b.Property<string>("SoCTHD")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaSP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SLSP")
                        .HasColumnType("int");

                    b.Property<string>("SoHD")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SoCTHD");

                    b.HasIndex("MaSP");

                    b.HasIndex("SoHD");

                    b.ToTable("CTHD");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.CTPhieuNhap", b =>
                {
                    b.Property<string>("SoCTPN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("DonGiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChuCTPN")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaSP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SLN")
                        .HasColumnType("int");

                    b.Property<string>("SoPN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("ThanhTienNhap")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SoCTPN");

                    b.HasIndex("MaSP");

                    b.HasIndex("SoPN");

                    b.ToTable("CTPNHAP");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.CTPhieuNhapNL", b =>
                {
                    b.Property<string>("SoCTPNNL")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("DonGiaNhapNL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaNL")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("SLNhapNL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SoPNNL")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("ThanhTienNhapNL")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SoCTPNNL");

                    b.HasIndex("MaNL");

                    b.HasIndex("SoPNNL");

                    b.ToTable("CTPHIEUNHAP_NL");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.CongThuc", b =>
                {
                    b.Property<string>("MaCT")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChuCT")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaNL")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("SoLuongNL")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaCT");

                    b.HasIndex("MaNL");

                    b.HasIndex("MaSP");

                    b.ToTable("CONGTHUC");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.DatBan", b =>
                {
                    b.Property<string>("MaDatBan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChuDat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeSpan?>("GioDat")
                        .HasColumnType("time");

                    b.Property<string>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoBan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SoLuongNguoi")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiDat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDatBan");

                    b.HasIndex("MaKH");

                    b.HasIndex("SoBan");

                    b.ToTable("DATBAN");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.HoaDon", b =>
                {
                    b.Property<string>("SoHD")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChuHD")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("GiamGiaHD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HoaDonKyNhan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV_PC")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV_PV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("PhuThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SoBan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("TGRa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TGVao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ThueVAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiHD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SoHD");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV_PC");

                    b.HasIndex("MaNV_PV");

                    b.HasIndex("SoBan");

                    b.ToTable("HOADON");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("GhiChuKH")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDTKH")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenKH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKH");

                    b.ToTable("KH");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.KhuVuc", b =>
                {
                    b.Property<string>("SoKV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChuKV")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("PhuThuKV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan?>("TGDong")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TGMo")
                        .HasColumnType("time");

                    b.Property<string>("TenKV")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiKhu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SoKV");

                    b.ToTable("KV");

                    b.HasData(
                        new
                        {
                            SoKV = "KV01",
                            PhuThuKV = 0m,
                            TenKV = "Tầng trệt (Máy lạnh)",
                            TrangThaiKhu = "Mở cửa"
                        },
                        new
                        {
                            SoKV = "KV02",
                            PhuThuKV = 5000m,
                            TenKV = "Sân thượng (Hút thuốc)",
                            TrangThaiKhu = "Mở cửa"
                        });
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.KhuyenMai", b =>
                {
                    b.Property<string>("MaKM")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DieuKienKM")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChuKM")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("GiaTriKM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiKM")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayBD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKT")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKM")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThaiKM")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKM");

                    b.ToTable("KHUYENMAI");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.LichSuKho", b =>
                {
                    b.Property<string>("MaLSKho")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChuLSK")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiGD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNL")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NguoiThucHien")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("SoLuongGD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ThoiGianGD")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLSKho");

                    b.HasIndex("MaNL");

                    b.HasIndex("NguoiThucHien");

                    b.ToTable("LICHSU_KHO");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.LoaiNV", b =>
                {
                    b.Property<string>("MaLoaiNV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CVLoaiNV")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChuLoaiNV")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("HsLoaiNV")
                        .HasColumnType("float");

                    b.Property<string>("TenLoaiNV")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaLoaiNV");

                    b.ToTable("LOAINV");

                    b.HasData(
                        new
                        {
                            MaLoaiNV = "LNV01",
                            HsLoaiNV = 2.0,
                            TenLoaiNV = "Quản lý"
                        },
                        new
                        {
                            MaLoaiNV = "LNV02",
                            HsLoaiNV = 1.2,
                            TenLoaiNV = "Pha chế"
                        },
                        new
                        {
                            MaLoaiNV = "LNV03",
                            HsLoaiNV = 1.0,
                            TenLoaiNV = "Phục vụ"
                        });
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.LoaiSP", b =>
                {
                    b.Property<string>("MaLoaiSP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BaoQuan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChuLoaiSP")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("LaHangDeVo")
                        .HasColumnType("bit");

                    b.Property<string>("TenLoaiSP")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaLoaiSP");

                    b.ToTable("LOAISP");

                    b.HasData(
                        new
                        {
                            MaLoaiSP = "LSP01",
                            LaHangDeVo = false,
                            TenLoaiSP = "Cà phê"
                        },
                        new
                        {
                            MaLoaiSP = "LSP02",
                            LaHangDeVo = false,
                            TenLoaiSP = "Trà trái cây"
                        },
                        new
                        {
                            MaLoaiSP = "LSP03",
                            LaHangDeVo = true,
                            TenLoaiSP = "Bánh ngọt"
                        });
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.NguyenLieu", b =>
                {
                    b.Property<string>("MaNL")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DVTNL")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("DonGiaNL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChuNL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MucCanhBao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SoLuongTon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenNL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThaiNL")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNL");

                    b.ToTable("NGUYENLIEU");

                    b.HasData(
                        new
                        {
                            MaNL = "NL01",
                            DVTNL = "Kg",
                            DonGiaNL = 150000m,
                            SoLuongTon = 10m,
                            TenNL = "Hạt Cà Phê Robusta"
                        },
                        new
                        {
                            MaNL = "NL02",
                            DVTNL = "Lon",
                            DonGiaNL = 25000m,
                            SoLuongTon = 20m,
                            TenNL = "Sữa Đặc"
                        });
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.NhaCungCap", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChiNCC")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChuNCC")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDTNCC")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SoTKNCC")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaNCC");

                    b.ToTable("NCC");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChiNV_NT")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChiNV_TT")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChuNV")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhAnhNV")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoNV")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MaLoaiNV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgaySinhNV")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("PhaiNV")
                        .HasColumnType("bit");

                    b.Property<string>("SoBHXH")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SoBHYT")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SoCCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoDTNV")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SoTKNV")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNgHNV")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiNV")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrinhDoHV")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaLoaiNV");

                    b.ToTable("NHANVIEN");

                    b.HasData(
                        new
                        {
                            MaNV = "NV01",
                            HoNV = "Nguyễn Văn",
                            MaLoaiNV = "LNV01",
                            PhaiNV = true,
                            TenNV = "An",
                            TrangThaiNV = "Đang làm"
                        },
                        new
                        {
                            MaNV = "NV02",
                            HoNV = "Trần Thị",
                            MaLoaiNV = "LNV02",
                            PhaiNV = false,
                            TenNV = "Bình",
                            TrangThaiNV = "Đang làm"
                        });
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.PhanQuyen", b =>
                {
                    b.Property<string>("MaPQ")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTaPQ")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenPQ")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPQ");

                    b.ToTable("PHANQUYEN");

                    b.HasData(
                        new
                        {
                            MaPQ = "PQ01",
                            MoTaPQ = "Toàn quyền hệ thống",
                            TenPQ = "Quản trị viên"
                        },
                        new
                        {
                            MaPQ = "PQ02",
                            MoTaPQ = "Quyền bán hàng cơ bản",
                            TenPQ = "Nhân viên"
                        });
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.PhieuNhap", b =>
                {
                    b.Property<string>("SoPN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChuPN")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaNCC")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhapHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("TongTienNhap")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SoPN");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaNV");

                    b.ToTable("PNHAP");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.PhieuNhapNL", b =>
                {
                    b.Property<string>("SoPNNL")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChuPNNL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaNCC")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayNhapNL")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongTienNhapNL")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SoPNNL");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaNV");

                    b.ToTable("PHIEUNHAP_NL");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DVT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KichThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaLoaiSP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThaiSP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSP");

                    b.HasIndex("MaLoaiSP");

                    b.ToTable("SANPHAM");

                    b.HasData(
                        new
                        {
                            MaSP = "SP01",
                            DVT = "Ly",
                            DonGia = 25000m,
                            MaLoaiSP = "LSP01",
                            TenSP = "Cà phê đen đá",
                            TrangThaiSP = "Đang bán"
                        },
                        new
                        {
                            MaSP = "SP02",
                            DVT = "Ly",
                            DonGia = 30000m,
                            MaLoaiSP = "LSP01",
                            TenSP = "Bạc xỉu",
                            TrangThaiSP = "Đang bán"
                        },
                        new
                        {
                            MaSP = "SP03",
                            DVT = "Ly",
                            DonGia = 45000m,
                            MaLoaiSP = "LSP02",
                            TenSP = "Trà đào cam sả",
                            TrangThaiSP = "Đang bán"
                        });
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.SanPham_KhuyenMai", b =>
                {
                    b.Property<string>("MaSP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKM")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaSP", "MaKM");

                    b.HasIndex("MaKM");

                    b.ToTable("SANPHAM_KHUYENMAI");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaPQ")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThaiTK")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TenDangNhap");

                    b.HasIndex("MaNV")
                        .IsUnique();

                    b.HasIndex("MaPQ");

                    b.ToTable("TAIKHOAN");

                    b.HasData(
                        new
                        {
                            TenDangNhap = "admin",
                            MaNV = "NV01",
                            MaPQ = "PQ01",
                            MatKhau = "123456",
                            TrangThaiTK = "Hoạt động"
                        },
                        new
                        {
                            TenDangNhap = "nhanvien1",
                            MaNV = "NV02",
                            MaPQ = "PQ02",
                            MatKhau = "123456",
                            TrangThaiTK = "Hoạt động"
                        });
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.ThanhToan", b =>
                {
                    b.Property<string>("MaTT")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhuongThucTT")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoHD")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("SoTienTT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ThoiGianTT")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiTT")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTT");

                    b.HasIndex("SoHD");

                    b.ToTable("THANHTOAN");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.Ban", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.KhuVuc", "KhuVuc")
                        .WithMany("Bans")
                        .HasForeignKey("SoKV");

                    b.Navigation("KhuVuc");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.CTHD", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSP");

                    b.HasOne("WebCoffee.BackendServer.Data.Entities.HoaDon", "HoaDon")
                        .WithMany("CTHDs")
                        .HasForeignKey("SoHD");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.CTPhieuNhap", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSP");

                    b.HasOne("WebCoffee.BackendServer.Data.Entities.PhieuNhap", "PhieuNhap")
                        .WithMany("CTPhieuNhaps")
                        .HasForeignKey("SoPN");

                    b.Navigation("PhieuNhap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.CTPhieuNhapNL", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("MaNL");

                    b.HasOne("WebCoffee.BackendServer.Data.Entities.PhieuNhapNL", "PhieuNhapNL")
                        .WithMany()
                        .HasForeignKey("SoPNNL");

                    b.Navigation("NguyenLieu");

                    b.Navigation("PhieuNhapNL");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.CongThuc", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("CongThucs")
                        .HasForeignKey("MaNL");

                    b.HasOne("WebCoffee.BackendServer.Data.Entities.SanPham", "SanPham")
                        .WithMany("CongThucs")
                        .HasForeignKey("MaSP");

                    b.Navigation("NguyenLieu");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.DatBan", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH");

                    b.HasOne("WebCoffee.BackendServer.Data.Entities.Ban", "Ban")
                        .WithMany()
                        .HasForeignKey("SoBan");

                    b.Navigation("Ban");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.HoaDon", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH");

                    b.HasOne("WebCoffee.BackendServer.Data.Entities.NhanVien", "NhanVienPhaChe")
                        .WithMany()
                        .HasForeignKey("MaNV_PC")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebCoffee.BackendServer.Data.Entities.NhanVien", "NhanVienPhucVu")
                        .WithMany()
                        .HasForeignKey("MaNV_PV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebCoffee.BackendServer.Data.Entities.Ban", "Ban")
                        .WithMany()
                        .HasForeignKey("SoBan");

                    b.Navigation("Ban");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVienPhaChe");

                    b.Navigation("NhanVienPhucVu");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.LichSuKho", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("MaNL");

                    b.HasOne("WebCoffee.BackendServer.Data.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NguoiThucHien");

                    b.Navigation("NguyenLieu");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.NhanVien", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.LoaiNV", "LoaiNV")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaLoaiNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiNV");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.PhieuNhap", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNCC");

                    b.HasOne("WebCoffee.BackendServer.Data.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV");

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.PhieuNhapNL", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNCC");

                    b.HasOne("WebCoffee.BackendServer.Data.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV");

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.SanPham", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.LoaiSP", "LoaiSP")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoaiSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSP");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.SanPham_KhuyenMai", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany("SanPham_KhuyenMais")
                        .HasForeignKey("MaKM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCoffee.BackendServer.Data.Entities.SanPham", "SanPham")
                        .WithMany("SanPham_KhuyenMais")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.TaiKhoan", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("WebCoffee.BackendServer.Data.Entities.TaiKhoan", "MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCoffee.BackendServer.Data.Entities.PhanQuyen", "PhanQuyen")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaPQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("PhanQuyen");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.ThanhToan", b =>
                {
                    b.HasOne("WebCoffee.BackendServer.Data.Entities.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("SoHD");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.HoaDon", b =>
                {
                    b.Navigation("CTHDs");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.KhuVuc", b =>
                {
                    b.Navigation("Bans");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.KhuyenMai", b =>
                {
                    b.Navigation("SanPham_KhuyenMais");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.LoaiNV", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.LoaiSP", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.NguyenLieu", b =>
                {
                    b.Navigation("CongThucs");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.NhanVien", b =>
                {
                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.PhanQuyen", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.PhieuNhap", b =>
                {
                    b.Navigation("CTPhieuNhaps");
                });

            modelBuilder.Entity("WebCoffee.BackendServer.Data.Entities.SanPham", b =>
                {
                    b.Navigation("CongThucs");

                    b.Navigation("SanPham_KhuyenMais");
                });
#pragma warning restore 612, 618
        }
    }
}
